# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2022'

steps:

- task: NuGetCommand@2
  displayName: NuGet v2 Restore
  inputs:
    command: restore                      
    restoreSolution: '**/*.sln'             ## Required when command = restore. Path to solution, packages.config, or project.json. Default: **/*.sln.
    feedsToUse: 'select'                    ## Required. Feeds to use. 'select' | 'config'. Alias: selectOrConfig. Default: select.
    includeNuGetOrg: true                   ## Use packages from upstream (NuGet.org)

#needs to run only once
#command to include the .NET 7 SDK
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 7.x
#command to include maui
#- task: CmdLine@2
#  inputs:
#    script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
  name: 'Build'
  inputs:
    command: 'build'
    projects: '**\Time2Plan.sln'

- task: DotNetCoreCLI@2
  name: 'Test'
  inputs:
    command: 'test'
    projects: '**\Time2Plan.sln'